controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [mppi]
    mppi:
      rt_freq: 30.0
      plugin: easynav_mppi_controller/MPPIController
      max_linear_velocity: 0.8  
      max_angular_velocity: 0.5
      safety_radius: 1.5

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [costmap_localizer]
    costmap_localizer:
      rt_freq: 50.0
      freq: 5.0
      reseed_freq: 1.0
      plugin: easynav_costmap_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.05
      noise_rotation: 0.1
      noise_translation_to_rotation: 0.1
      initial_pose:
        x: 0.0
        y: 0.0
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.01

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap_manager]
    costmap_manager:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      package: nav2_playground                # easynav_workshop_testcase
      map_path_file: maps/aws_house.yaml      # maps/home.yaml
      filters: [inflation, obstacles]
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.3
        cost_scaling_factor: 3.0
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [costmap_planner]
    costmap_planner:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      robot_radius: 0.25
      cost_factor: 3.0

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan

system_node:
  ros__parameters:
    use_sim_time: true
    position_tolerance: 0.3
    angle_tolerance: 0.15