patrolling_node:
  ros__parameters:
    use_sim_time: true
    frame_id: map
    waypoints: [wp1, wp2, wp3, wp4]
    wp1: [10.544, 0.195, 0.300]  
    wp2: [2.042, -9.741, -2.964]
    wp3: [-8.826, -0.309, 1.754]
    wp4: [-8.492, 18.576, 1.556] 