name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
      - cron: '0 0 * * 6'     
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: jazzy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: nav2_playground
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: jazzy
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/exercises/nav2/nav2_playground/thirdparty.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false